language: scala
scala:
  - 2.11.7
jdk: oraclejdk8
sudo: true
cache:
  directories:
  - $HOME/.ivy2/cache
services:
  - elasticsearch
install:
  - cd node/json-frame/ && npm install && cd ../..
before_script:
  - cp conf/travis.conf conf/test.conf
branches:
  only:
    - master
